# Generated by Django 5.0.4 on 2024-04-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to="uploads/temp_download"),
        ),
    ]
