# Generated by Django 5.0.4 on 2024-04-30 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0003_userfoldergoogledrive"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfoldergoogledrive",
            old_name="user_id",
            new_name="user",
        ),
    ]
