# Generated by Django 5.0.4 on 2024-04-30 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0004_rename_user_id_userfoldergoogledrive_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfoldergoogledrive",
            old_name="folder_id",
            new_name="folder_drive_id",
        ),
    ]
