# Generated by Django 5.0.4 on 2024-05-01 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0005_rename_folder_id_userfoldergoogledrive_folder_drive_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfoldergoogledrive",
            name="folder_drive_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="userfoldergoogledrive",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
