# Generated by Django 5.0.4 on 2024-05-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0006_alter_userfoldergoogledrive_folder_drive_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfoldergoogledrive",
            name="folder_drive_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
